/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2019-10-22 07:39:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.kh.member.model.vo.Member;

public final class ajaxTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1570758416415L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    Member m = (Member)session.getAttribute("member");
    
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header/responsive.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<header class=\"header_area\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand logo_h\" href=\"/\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/img/logo.png\" width=\"165\" height=\"80\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" \r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" \r\n");
      out.write("\t\t\t\tdata-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls = \"navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-expand=\"false\"\r\n");
      out.write("\t\t\t\taria-label = \"Toggle navigation\" >\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse offset\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav menu-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/noticeList\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/boardList\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/views/Test/ajaxTest.jsp\">AjaxTest</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/photoList\">사진게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/views/Test/apiTest.jsp\">APITest</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"right-button\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t");
if( m == null ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><button class=\"btn btn-danger\" onclick=\"location.href='/views/member/login.jsp'\">로그인</button></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><button class=\"btn btn-danger\" onclick=\"location.href='/views/member/join.jsp'\">회원가입</button></li>\r\n");
      out.write("\t\t\t\t\t\t");
}else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><button class=\"btn btn-danger\" onclick=\"location.href='/mypage?memberId=");
      out.print(m.getMemberId());
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(m.getMemberName());
      out.write("</button></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><button class=\"btn btn-danger\" onclick=\"location.href='/logout'\">로그아웃</button></li>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</header>");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\" style=\"color:black;\">\r\n");
      out.write("\t\t\t<h3>1. Ajax 서버에 전송값 보내기</h3>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"msg1\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" onclick=\"jsFunction();\">JS로 보내기</button>\r\n");
      out.write("\t\t\t<button id=\"jQ1\" class=\"btn btn-primary\">jQuery로 보내기</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>2. 버튼클릭 시 서버에서 보낸 값 사용자가 수신</h3>\r\n");
      out.write("\t\t\t<button id=\"jQ2\" class=\"btn btn-primary\">서버에서 보낸 값 사용자가 수신</button>\r\n");
      out.write("\t\t\t<p id =\"p2\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>3. 서버로 기본형 전송값을 보내고, 결과로 문자열을 받아서 처리</h3>\r\n");
      out.write("\t\t\t<p>두개의 숫자값을 보내고 더한값을 받아옴</p>\r\n");
      out.write("\t\t\t첫번째 숫자 : <input type=\"text\" id=\"firstNum\"><br>\r\n");
      out.write("\t\t\t두번째 숫자 : <input type=\"text\" id=\"secondNum\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ3\">실행</button>\r\n");
      out.write("\t\t\t<p id=\"p3\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>4. 서버로 Object형 전송값 보내기</h3>\r\n");
      out.write("\t\t\t이름 : <input type=\"text\" id=\"name\"><br>\r\n");
      out.write("\t\t\t나이 : <input type=\"text\" id=\"age\"><br>\r\n");
      out.write("\t\t\t주소 : <input type=\"text\" id=\"addr\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ4\">실행</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>5. 서버로 기본형 데이터를 보내고, 결과로 객체를 받아서 처리</h3>\r\n");
      out.write("\t\t\t<p>JSON을 사용</p>\r\n");
      out.write("\t\t\t유저 번호 입력 : <input type=\"text\" id=\"userNum\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ5\">실행</button>\r\n");
      out.write("\t\t\t<p id=\"p5\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>6. 서버로 기본형 전송값을 보내고, 결과로 리스트객체를 받아서 처리</h3>\r\n");
      out.write("\t\t\t<p>JSON객체이용</p>\r\n");
      out.write("\t\t\t<p>유저번호를 보내서 해당 유저정보 가져오기 -> 없는 경우에는 전체 리스트 가져오기</p>\r\n");
      out.write("\t\t\t유저번호 입력(번호):<input type=\"text\" id=\"userNum2\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ6\">실행</button>\r\n");
      out.write("\t\t\t<p id=\"p6\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>7. 여러 전송값을 보내고, 결과로 리스트를 받아서 처리</h3>\r\n");
      out.write("\t\t\t유저번호입력(번호,번호,번호) : <input type=\"text\" id=\"userNum3\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ7\">실행</button>\r\n");
      out.write("\t\t\t<p id=\"p7\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>8. 여러 전송값을 보내고, 결과로 맵객체를 받아서 처리</h3>\r\n");
      out.write("\t\t\t유저번호입력(번호,번호,번호) : <input type=\"text\" id=\"userNum4\"><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ8\">실행</button>\r\n");
      out.write("\t\t\t<p id=\"p8\" class=\"border border-danger\"></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>9. 서버 유저 정보 테이블로 표현하기</h3>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ9\">실행</button>\r\n");
      out.write("\t\t\t<table id=\"userTbl\" class=\"table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>10. GSON을 이용한 LIST반환</h3>\r\n");
      out.write("\t\t\t<p>GSON 사용</p>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ10\">실행</button>\r\n");
      out.write("\t\t\t<select id=\"select10\">\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3>11. GSON을 이용한 MAP반환</h3>\r\n");
      out.write("\t\t\t<p>GSON 사용</p>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"jQ11\">실행</button>\r\n");
      out.write("\t\t\t<select id=\"select11\">\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/* JS 방식 */\r\n");
      out.write("\t\tfunction jsFunction(){\r\n");
      out.write("\t\t\t// 1. XMLHttpRequest 객체 생성\r\n");
      out.write("\t\t\tvar xhttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\tvar msg = document.getElementById(\"msg1\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 2. 요청정보 설정\r\n");
      out.write("\t\t\txhttp.open(\"GET\",\"/ajaxTest1?msg=\"+msg,true);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 3. 데이터 처리에 따라 작동할 함수 설정\r\n");
      out.write("\t\t\txhttp.onreadystatechange = function(){\r\n");
      out.write("\t\t\t\tif(this.readyState==4 && this.status == 200){\t// 정상 처리된 경우\r\n");
      out.write("\t\t\t\t\tconsole.log(\"서버 전송 성공\");\r\n");
      out.write("\t\t\t\t}else if(this.readyState == 4 && this.status == 404){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"서버 전송 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 서버에게 요청\r\n");
      out.write("\t\t\txhttp.send();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* jQuery 방식 */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#jQ1\").click(function(){\r\n");
      out.write("\t\t\tvar message = $(\"#msg1\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t// 2. 요청 정보 설정\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest1\",\t\t// 넘겨질 주소\r\n");
      out.write("\t\t\t\tdata : {msg:message},\t// 객체타입 - 키(msg) 값 (message)\r\n");
      out.write("\t\t\t\ttype : \"get\",\t\t\t// 방식\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 3. 데이터 처리에 따라 작동할 함수 설정 \r\n");
      out.write("\t\t\t\tsuccess : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"서버 전송 성공!\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"서버 전송 실패\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcomplete : function(){\t\t// complete : 성공하던 실패하던 무조건 호출\r\n");
      out.write("\t\t\t\t\tconsole.log(\"무조건 호출\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#jQ2\").click(function(){\r\n");
      out.write("\t\t\t// 보낼 테이터가 없으므로 따로 data를 넣어서 넘겨주지않는다.\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest2\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t// 매개변수를 통해 값을 가져온다.\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t$(\"#p2\").html(data);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 값 주고 계산된값 받기\r\n");
      out.write("\t\t$(\"#jQ3\").click(function(){\r\n");
      out.write("\t\t\t var firstNum = $(\"#firstNum\").val();\r\n");
      out.write("\t\t\t var secondNum = $(\"#secondNum\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 값 설정해서 넘겨주기\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest3\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {firstNum:firstNum,secondNum:secondNum},\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 결과에 따라 값 받아오기\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t// 받아오는 data는 string으로 넘어온다\r\n");
      out.write("\t\t\t\t\t$(\"#p3\").html(data + 1);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 서버로 Object 객체 보내기\r\n");
      out.write("\t\t$(\"#jQ4\").click(function(){\r\n");
      out.write("\t\t\tvar name = $(\"#name\").val();\r\n");
      out.write("\t\t\tvar age = $(\"#age\").val();\r\n");
      out.write("\t\t\tvar addr = $(\"#addr\").val();\r\n");
      out.write("\t\t\tvar student = {name:name, age:age, addr:addr};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest4\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : student,\t\t// 넘겨주는 값이 객체타입이므로 그냥 넘겨주면된다.\r\n");
      out.write("\t\t\t\tsuccess : function(){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"성공\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 서버로 기본형 데이터를 보내고 객체를 받아오기 (json사용)\r\n");
      out.write("\t\t$('#jQ5').click(function(){\r\n");
      out.write("\t\t\tvar userNum = $(\"#userNum\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest5\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {userNum:userNum},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar userNo = data.userNo;\r\n");
      out.write("\t\t\t\t\t// 인코딩되서 넘어왔기때문에 디코딩\r\n");
      out.write("\t\t\t\t\tvar userName = decodeURIComponent(data.userName);\t\r\n");
      out.write("\t\t\t\t\tvar userAddr = decodeURIComponent(data.userAddr);\r\n");
      out.write("\t\t\t\t\t$(\"#p5\").html('유저번호 : ' + userNo + \"<br>\" + \r\n");
      out.write("\t\t\t\t\t\t\t\t'유저이름 : ' + userName + \"<br>\" + \r\n");
      out.write("\t\t\t\t\t\t\t\t\"주소 : \"+ userAddr);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 서버로 기본형 데이터를 보내고 결과로 리스트객체로 받아서처리\r\n");
      out.write("\t\t$(\"#jQ6\").click(function(){\r\n");
      out.write("\t\t\tvar userNum = $(\"#userNum2\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest6\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {userNum:userNum},\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar resultText = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar userNo = data[i].userNo;\r\n");
      out.write("\t\t\t\t\t\t// 인코딩되서 넘어왔기때문에 디코딩\r\n");
      out.write("\t\t\t\t\t\tvar userName = decodeURIComponent(data[i].userName);\t\r\n");
      out.write("\t\t\t\t\t\tvar userAddr = decodeURIComponent(data[i].userAddr);\r\n");
      out.write("\t\t\t\t\t\tresultText += \"유저 번호 : \" +userNo+ \"/유저 이름 : \" +userName+ \"/주소 : \" +userAddr+\"<br>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#p6\").html(resultText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#jQ7\").click(function(){\r\n");
      out.write("\t\t\tvar userNum = $(\"#userNum3\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest7.do\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tdata:{userNum:userNum},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tvar resultText = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar userNo = data[i].userNo;\r\n");
      out.write("\t\t\t\t\t\t// 인코딩되서 넘어왔기때문에 디코딩\r\n");
      out.write("\t\t\t\t\t\tvar userName = decodeURIComponent(data[i].userName);\t\r\n");
      out.write("\t\t\t\t\t\tvar userAddr = decodeURIComponent(data[i].userAddr);\r\n");
      out.write("\t\t\t\t\t\tresultText += \"유저 번호 : \" +userNo+ \"/유저 이름 : \" +userName+ \"/주소 : \" +userAddr+\"<br>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#p7\").html(resultText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 여러 전송값을 보내고, 결과로 맵객체를 받아서 처리\r\n");
      out.write("\t\t$(\"#jQ8\").click(function(){\r\n");
      out.write("\t\t\tvar userNum = $(\"#userNum4\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest8.do\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tdata:{userNum:userNum},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultText = \"\";\r\n");
      out.write("\t\t\t\t\tvar keys = Object.keys(data); // 키값만 한번에 추출\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i<keys.length;i++){\r\n");
      out.write("\t\t\t\t\t\tvar userNo = data[keys[i]].userNo;\r\n");
      out.write("\t\t\t\t\t\tvar userName = decodeURIComponent(data[keys[i]].userName);\t\r\n");
      out.write("\t\t\t\t\t\tvar userAddr = decodeURIComponent(data[keys[i]].userAddr);\r\n");
      out.write("\t\t\t\t\t\tresultText += \"유저 번호 : \" +userNo+ \"/유저 이름 : \" +userName+ \"/주소 : \" +userAddr+\"<br>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#p8\").html(resultText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 서버 유저 정보 테이블로 표현하기\r\n");
      out.write("\t\t$(\"#jQ9\").click(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest9.do\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tvar tbody = $(\"#userTbl tbody\");\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i<data.length; i++){\r\n");
      out.write("\t\t\t\t\t\tvar tr = $(\"<tr>\");\t// 닫는태그안하면 자동으로 닫아줌\r\n");
      out.write("\t\t\t\t\t\tvar noTd = $(\"<td>\").html(data[i].userNo);\r\n");
      out.write("\t\t\t\t\t\tvar nameTd = $(\"<td>\").html(decodeURIComponent(data[i].userName));\r\n");
      out.write("\t\t\t\t\t\tvar addrTd = $(\"<td>\").html(decodeURIComponent(data[i].userAddr));\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttr.append(noTd).append(nameTd).append(addrTd);\r\n");
      out.write("\t\t\t\t\t\ttbody.append(tr);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// GSON 사용해서 List반환\r\n");
      out.write("\t\t$(\"#jQ10\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest10.do\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar select = $(\"#select10\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var index in data){\t// Java의 foreach문과 동일\r\n");
      out.write("\t\t\t\t\t\tvar option = $(\"<option>\");\r\n");
      out.write("\t\t\t\t\t\toption.html(data[index].userName);\r\n");
      out.write("\t\t\t\t\t\tselect.append(option);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// GSON 사용해서 Map반환\r\n");
      out.write("\t\t$(\"#jQ11\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/ajaxTest11.do\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tvar select = $(\"#select11\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var key in data){\t// for in 문으로 map의 key값을 순서대로 가져와서 사용\r\n");
      out.write("\t\t\t\t\t\tvar option = $(\"<option>\");\r\n");
      out.write("\t\t\t\t\t\toption.html(data[key].userName);\r\n");
      out.write("\t\t\t\t\t\tselect.append(option);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
