/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2019-10-30 05:16:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.tomato.member.model.vo.MemberAddress;
import java.util.ArrayList;
import java.util.StringTokenizer;
import kr.co.tomato.member.model.vo.Member;
import java.util.ArrayList;
import kr.co.tomato.member.model.vo.Member;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1572411278990L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1572352628901L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.tomato.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.StringTokenizer");
    _jspx_imports_classes.add("kr.co.tomato.member.model.vo.MemberAddress");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Member m = (Member) session.getAttribute("member");
		
	ArrayList<MemberAddress> list = (ArrayList<MemberAddress>)request.getAttribute("addrList");

	// 우리집 주소 (db) : '주소 /상세주소' 형태로 저장  => 토큰으로 분리해서 사용
	String addr = null;
	String detailAddr = null;
	if(!m.getAddress().equals("/")){
		StringTokenizer token = new StringTokenizer(m.getAddress(),"/");
		addr = token.nextToken();
		if(token.hasMoreElements()){
			detailAddr = token.nextToken();
		}else{
			detailAddr = null;
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>토마토마켓</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage_area {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage_box {\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\tpadding: 50px 10px 20px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".f-header {\r\n");
      out.write("\tpadding-bottom: 25px;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-img{\r\n");
      out.write("\twidth: 25px;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".f-icon-td {\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\tpadding: 0 10px 0 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tborder-top: 1px solid gray;\r\n");
      out.write("\tborder-bottom: 1px solid gray;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write(".btn-wrap{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin:30px 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write(".btn1{\r\n");
      out.write("\tborder:1 soild black;\r\n");
      out.write("\tborder-radius:1px;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tcolor:#878787;\r\n");
      out.write("\tfont-size:13px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("}\r\n");
      out.write(".btn-2{\r\n");
      out.write("\tmargin-left:10px;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tborder:1px solid #c42026;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tcolor:#c42026;\r\n");
      out.write("}\r\n");
      out.write(".addressAdd-btn{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground: #C42026;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header/header.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tfunction searchWord(){\r\n");
      out.write("\t\t\t$.ajax ({\r\n");
      out.write("\t\t\t\turl : \"/headerSearchBox\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tsuccess : function (data) { \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar searchDiv = $(\".header-searchList\");\r\n");
      out.write("\t\t\t\t\t\tvar searchUl = $(\"#ticker\");\r\n");
      out.write("\t\t\t\t\t\tsearchDiv.empty();\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<10;i++){\r\n");
      out.write("\t\t\t\t\t\t/* console.log(decodeURIComponent(data[i].searchContent)); */\r\n");
      out.write("\t\t\t\t\t\tvar searchP = $(\"<p>\");\r\n");
      out.write("\t\t\t\t\t\tvar searchSpan = $(\"<span class='searchNum'>\").html(i+1);\r\n");
      out.write("\t\t\t\t\t\tvar searchA = $(\"<a href='/search?keyword=\"+decodeURIComponent(data[i].searchContent)+\"' class='searchListA'>\").html(decodeURIComponent(data[i].searchContent));\r\n");
      out.write("\t\t\t\t\t\tsearchP.append(searchSpan).append(searchA);\r\n");
      out.write("\t\t\t\t\t\tsearchDiv.append(searchP);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar searchLi = $(\"<li>\");\r\n");
      out.write("\t\t\t\t\t\tvar searchA1 = $(\"<a href='/search?keyword=\"+decodeURIComponent(data[i].searchContent)+\"'>\").html(decodeURIComponent(data[i].searchContent));\r\n");
      out.write("\t\t\t\t\t\tvar searchSpan1 = $(\"<span class='sort-num'>\").html(i+1);\r\n");
      out.write("\t\t\t\t\t\tsearchLi.append(searchA1).prepend(searchSpan1);\r\n");
      out.write("\t\t\t\t\t\tsearchUl.append(searchLi);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".b-navbar\").append(searchDiv);\r\n");
      out.write("\t\t\t\t\t$(\".searchBox\").append(searchUl);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\ttimer = setInterval(function () {\r\n");
      out.write("\t\t\t//----------------------------------------------------------------------------------\r\n");
      out.write("\t\t\t\t\t\t//----------------------------------------------------------------------------------\r\n");
      out.write("\t\t}, 2000); // 30초에 한번씩 받아온다.\t \r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\tsearchWord();\r\n");
      out.write("\t    //인기검색어\r\n");
      out.write("   \t\tvar ticker = function()\r\n");
      out.write("\t    {\r\n");
      out.write("\t        setTimeout(function(){\r\n");
      out.write("\t            $('#ticker li:first').animate( {marginTop: '-20px'}, 400, function()\r\n");
      out.write("\t            {\r\n");
      out.write("\t                $(this).detach().appendTo('ul#ticker').removeAttr('style');\r\n");
      out.write("\t            });\r\n");
      out.write("\t            ticker();\r\n");
      out.write("\t        }, 3000);\r\n");
      out.write("\t    };\r\n");
      out.write("\t    ticker();\r\n");
      out.write("\t    \r\n");
      out.write("\t    //인기검색어 hover/slideToggle()\r\n");
      out.write("/* \t    \r\n");
      out.write("\t    $(\".list\").hover(function() {\r\n");
      out.write("\t    \t$(\".header-searchList\").slideToggle();\r\n");
      out.write("\t    });\r\n");
      out.write("\t */\t\r\n");
      out.write("\t\t//nav mouse event\r\n");
      out.write("\t\t$(\"#navFunc\").mouseenter(function(){\r\n");
      out.write("\t\t\t$(\"#cate\").slideDown();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#cate\").mouseleave(function(){\r\n");
      out.write("\t\t\t$(\"#cate\").slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//인기검색어\r\n");
      out.write("\t\t$(\".list\").mouseenter(function(){\r\n");
      out.write("\t\t\t$(\".header-searchList\").slideDown();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".header-searchList\").mouseleave(function(){\r\n");
      out.write("\t\t\t$(\".header-searchList\").slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//연관검색어\r\n");
      out.write("\t\t//header-searchBox 클릭\r\n");
      out.write("\t\t//header-searchBox-list\r\n");
      out.write("\t\t$(\"#header-searchBox\").click(function(){\r\n");
      out.write("\t\t\t$(\".header-searchBox-list\").slideDown();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".header-searchBox-list\").mouseleave(function(){\r\n");
      out.write("\t\t\t$(\".header-searchBox-list\").slideUp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//top버튼\r\n");
      out.write("\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t        if ($(this).scrollTop() > 400) {\r\n");
      out.write("\t\t            $('.cate-go').fadeIn();\r\n");
      out.write("\t\t        } else {\r\n");
      out.write("\t\t            $('.cate-go').fadeOut();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    });\t   \r\n");
      out.write("\t    $(window).scroll(function() {\r\n");
      out.write("\t        if ($(this).scrollTop() > 300) {\r\n");
      out.write("\t            $('.page-top').fadeIn();\r\n");
      out.write("\t        } else {\r\n");
      out.write("\t            $('.page-top').fadeOut(); \r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    //TOP버튼\r\n");
      out.write("\t    $(\".page-top\").click(function() {\r\n");
      out.write("\t        $('html').animate({scrollTop : 0}, 600);\r\n");
      out.write("\t    });\r\n");
      out.write("/* \r\n");
      out.write("\t    //알림 버튼 슬라이드 토글\r\n");
      out.write("\t    $(\"#header-alarm\").hover(function() {\r\n");
      out.write("\t    \t$(\".header-alarmBox\").slideToggle();\r\n");
      out.write("\t    });\r\n");
      out.write(" */\t    \r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"header1\">\r\n");
      out.write("\t\t\t<div class=\"con\">\r\n");
      out.write("\t\t\t\t<a href=\"https://apps.apple.com/app/id395672275\" class=\"header-a\" target=\"_blank\"><img id=\"download\" src=\"/img/download.png\"><span>앱다운로드</span></a>\r\n");
      out.write("\t\t\t\t<span id=\"head1\">\r\n");
      out.write("\t\t\t\t<a href=\"/mypage?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"header-a\">마이페이지</a>\r\n");
      out.write("<!-- \t\t\t\t<a href=\"#\" class=\"header-a\" id=\"header-alarm\">알림 <img id=\"arrow\" src=\"/img/arrow.png\"></a>-->\r\n");
      out.write("\t\t\t\t<a href=\"/logout\" class=\"header-a\" id=\"logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"header-alarmBox\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"header2\">  \r\n");
      out.write("\t\t\t<div class=\"con\" style=\"position: relative\">\r\n");
      out.write("\t\t\t\t<a href=\"/login?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&pw=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.memberPw }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"a\"><img id=\"logo\" src=\"/img/tomatoLogo.png\"></a>\r\n");
      out.write("\t\t\t\t<input type=\"text\" id=\"header-searchBox\" placeholder=\"지역, 상품, 업체 등을 검색하세요\" >\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"searchIcon\"><img class=\"searchIcon-img\" src=\"/img/search.png\"></button>\r\n");
      out.write("\t\t\t\t<div class=\"my-menu\">\r\n");
      out.write("\t\t\t\t\t<span><a href=\"/views/enroll.jsp\" class=\"header-a\"><img src=\"/img/money.png\" id=\"money\">판매하기</a></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<span><a href=\"/myshopView?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&memberNo=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.memberNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"header-a\"><img src=\"/img/myMarket.png\" id=\"myMarket\">내 상점</a></span>\r\n");
      out.write("\t\t\t\t\t<span><a href=\"/chatList\" class=\"header-a\" id=\"talk-a\"><img src=\"/img/talk.png\" id=\"talk\">토마톡</a></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<!-- <div class=\"header-searchBox-list\">\r\n");
      out.write("\t\t\t\t\t최근검색어\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; margin-bottom: 18px; font-size: 16px;\">최근검색어</p>  \r\n");
      out.write("\t\t\t\t\t<div class=\"searchBox-list-con\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p>바나나<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p> \r\n");
      out.write("\t\t\t\t\t\t<p>당산역김밥<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p>\r\n");
      out.write("\t\t\t\t\t\t<p>바나나<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p>\r\n");
      out.write("\t\t\t\t\t\t<p>당산역김밥<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p>\r\n");
      out.write("\t\t\t\t\t\t<p>바나나<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p>\r\n");
      out.write("\t\t\t\t\t\t<p>당산역김밥<span class=\"searchList-delete\"><button type=\"button\">x</button></span></p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<nav>    \r\n");
      out.write("\t \t<div class=\"nav-hover\">\r\n");
      out.write("\t\t\t<div class=\"b-navbar\">\r\n");
      out.write("\t\t\t\t<span id=\"navFunc\">\r\n");
      out.write("\t\t\t\t\t<img class=\"nav-img\" src=\"/img/menu.png\">\r\n");
      out.write("\t\t\t\t\t<span id=\"cate-span\">카테고리 선택 > </span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<div class=\"block-div\" style=\"float:right;width: 280px;\">\r\n");
      out.write("\t\t\t\t<span style=\"line-height:40px;font-weight:bold;float:left;\">인기검색어</span>\r\n");
      out.write("\t\t\t\t\t<div class=\"searchBox\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t    <ul id=\"ticker\">\r\n");
      out.write("\t\t\t\t\t        <!-- <li><a href=\"#\"><span class=\"sort-num\"></span></a></li> -->\r\n");
      out.write("\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t   \t<div class=\"list\">▼</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header-searchList\">\r\n");
      out.write("\t\t\t\t\t\t<!-- <p><span class=\"SearchNum\"></span><a href=\"#\" class=\"searchListA\"></a></p> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"cate\">  \r\n");
      out.write("\t\t\t\t<ul class=\"cate1-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=여성의류\" class=\"header-a\">여성의류</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=남성의류\" class=\"header-a\">남성의류</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=뷰티/미용\" class=\"header-a\">뷰티/미용</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=디지털/가전\" class=\"header-a\">디지털/가전</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=도서/티켓\" class=\"header-a\">도서/티켓</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=스타굿즈\" class=\"header-a\">스타굿즈</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=생활/가구\" class=\"header-a\">생활/가구</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate1-li\"><a href=\"/search?keyword=&mainCategory=기타\" class=\"header-a\">기타</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\" id=\"cate2-ul1\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=상의\" class=\"header-a\">상의</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=하의\" class=\"header-a\">하의</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=원피스\" class=\"header-a\">원피스</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=스포츠\" class=\"header-a\">스포츠</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=아우터\" class=\"header-a\">아우터</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=여성의류&subCategory=신발\" class=\"header-a\">신발</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=남성의류&subCategory=상의\" class=\"header-a\">상의</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=남성의류&subCategory=하의\" class=\"header-a\">하의</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=남성의류&subCategory=스포츠\" class=\"header-a\">스포츠</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=남성의류&subCategory=아우터\" class=\"header-a\">아우터</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=남성의류&subCategory=신발\" class=\"header-a\">신발</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=뷰티/미용&subCategory=색조화장품\" class=\"header-a\">색조화장품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=뷰티/미용&subCategory=기초화장품\" class=\"header-a\">기초화장품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=뷰티/미용&subCategory=남성화장품\" class=\"header-a\">남성화장품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=뷰티/미용&subCategory=식품\" class=\"header-a\">식품</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=디지털/가전&subCategory=PC/노트북\" class=\"header-a\">PC/노트북</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=디지털/가전&subCategory=카메라\" class=\"header-a\">카메라</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=디지털/가전&subCategory=가전제품\" class=\"header-a\">가전제품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=디지털/가전&subCategory=게임\" class=\"header-a\">게임</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=도서/티켓&subCategory=상품권\" class=\"header-a\">상품권</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=도서/티켓&subCategory=도서\" class=\"header-a\">도서</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=도서/티켓&subCategory=티켓\" class=\"header-a\">티켓</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=도서/티켓&subCategory=기프티콘\" class=\"header-a\">기프티콘</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=스타굿즈&subCategory=보이그룹\" class=\"header-a\">보이그룹</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=스타굿즈&subCategory=걸그룹\" class=\"header-a\">걸그룹</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=스타굿즈&subCategory=기타\" class=\"header-a\">기타</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"cate2-ul\">\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=생활/가구&subCategory=생활용품\" class=\"header-a\">생활용품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=생활/가구&subCategory=주방용품\" class=\"header-a\">주방용품</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=생활/가구&subCategory=가구\" class=\"header-a\">가구</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"cate2-li\"><a href=\"/search?keyword=&mainCategory=생활/가구&subCategory=식품\" class=\"header-a\">식품</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"nav-border\"></div>\r\n");
      out.write("\t \r\n");
      out.write("\t<div class=\"page-top\">\r\n");
      out.write("\t\t<div class=\"page-top-div\"><a href=\"#header\" class=\"page-top-a\">TOP</a></div>\r\n");
      out.write("\t</div> \r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t $(function(){\r\n");
      out.write("         $(\"#talk-a\").click(function(event){\r\n");
      out.write("             event.preventDefault();\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("             var status = \"left=500px, top=100px, width=400px,  height=612px, menubar=no, status=no, scrollbar=yes, resizable=no\";\r\n");
      out.write("             window.open(\"/chatList?memberNo=\"+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.member.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', \"토마톡\", status);\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("         });\r\n");
      out.write("     });\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(\".searchIcon\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar search = $(\"#header-searchBox\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 비어있지않을때만\r\n");
      out.write("\t\t\tif(search != \"\"){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//alert(search);\r\n");
      out.write("\t\t\t\tlocation.href=\"/search?keyword=\"+search;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mypage_area\">\r\n");
      out.write("\t\t<div class=\"mypage_box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"f-header\">My page</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"f-content\"  style=\"position:relative\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<p>기본정보</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table style=\"margin-bottom:30px;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/email2.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 150px;\">이메일</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" style=\"width: 200px;\"><input class=\"input-info\" type=\"text\" id=\"email\" name=\"email\" value=\"");
      out.print(m.getEmail());
      out.write("\"readOnly></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/padlock.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" id=\"pw\" name=\"pw\" value=\"");
      out.print(m.getMemberPw());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:700px; padding-left:10px;\"><span id=\"chkMsg3\"></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/padlock.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"input-info\" type=\"password\" placeholder=\"비밀번호 확인\" id=\"rePw\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding-left:10px;\"><span id=\"chkMsg4\"></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/phone-call.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>핸드폰 번호</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(m.getPhone()==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"input-info\" type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"핸드폰 번호\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"input-info\" type=\"text\" id=\"phone\" name=\"phone\" value=\"");
      out.print(m.getPhone());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding-left:10px;\"><span id=\"chkMsg5\"></span></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/envelope.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>우편번호</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(m.getZipCode()==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"input-info\" type=\"text\" id=\"zipCode\" name=\"zipCode\" style=\"width:90px\" placeholder=\"우편번호\" readOnly></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input class=\"input-info\" type=\"text\" id=\"zipCode\" name=\"zipCode\" style=\"width:90px\" value=\"");
      out.print(m.getZipCode());
      out.write("\" readOnly></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"/img/sj/btn_zipcode.gif\" style=\"width:92px; height:28px; margin-left:10px; cursor:pointer; position:absolute; top:240px; right:605px;\" onclick=\"addrSearch();\" ></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/house.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(addr==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"input-info\" type=\"text\" id=\"addr\" name=\"addr\" style=\"width:300px\" placeholder=\"주소\" readOnly></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"input-info\" type=\"text\" id=\"addr\" name=\"addr\" style=\"width:300px\" value=\"");
      out.print(addr);
      out.write("\" readOnly></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/add.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 130px;\">상세주소</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(detailAddr==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"input-info\" type=\"text\" placeholder=\"상세주소\" id=\"detailAddr\" name=\"detailAddr\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\"><input class=\"input-info\" type=\"text\"  name=\"detailAddr\" id=\"detailAddr\" value=\"");
      out.print(detailAddr);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<p>추가정보</p>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/add.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 130px;\">회원 이름</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(m.getMemberName()==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\" style=\"width:900px;\" ><input class=\"input-info\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"이름\" id=\"memberName\" name=\"memberName\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"  style=\"width:900px;\" ><input class=\"input-info\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"memberName\" id=\"memberName\" value=\"");
      out.print(m.getMemberName());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/add.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 130px;\">은행</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(m.getMemberBank()==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input class=\"input-info\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"은행\" id=\"memberBank\" name=\"memberBank\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input class=\"input-info\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"memberBank\" id=\"memberBank\" value=\"");
      out.print(m.getMemberBank());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\"><img class=\"icon-img\" src=\"/img/add.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 130px;\">계좌번호</td>\r\n");
      out.write("\t\t\t\t\t\t");
if(m.getMemberAccount()==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input class=\"input-info\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"계좌번호\" id=\"memberAccount\" name=\"memberAccount\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input class=\"input-info\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"memberAccount\" id=\"memberAccount\" value=\"");
      out.print(m.getMemberAccount());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
for(MemberAddress mAddr : list) {
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"/updateAddr\" method=\"get\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"f-icon-td\" style=\"border-top:0\"><img class=\"icon-img\" src=\"/img/placeholder.png\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td  style=\"width: 150px; border-top:0\">관심 지역 </td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"city\" style=\"width: 205px; border-top:0\"><input class=\"input-info\" value=\"");
      out.print(mAddr.getAddrChoiceCity());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"gungu\" style=\"width: 205px; border-top:0\"><input class=\"input-info\" value=\"");
      out.print(mAddr.getAddrChoiceGungu());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"newCity\" style=\"width: 205px; border-top:0\">\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"area1-1\" name=\"h_area1-1\" style=\"width:192px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value='서울'>서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"newGungu\" style=\"width: 205px; border-top:0\">\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"area2-1\" name=\"h_area2-1\" style=\"width: 192px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected disabled hidden>-선택-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강남구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강서구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>관악구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>광진구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>구로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>금천구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>노원구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>동작구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>마포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>서초구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>성동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>성북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>송파구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>양청구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>용산구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>은평구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>종로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>중구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>중랑구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"myEmail\" value=\"");
      out.print(m.getEmail() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"oldGunguAddr\" value=\"");
      out.print(mAddr.getAddrChoiceGungu());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t<td  style=\"width: 115px; border-top:0\"><button type=\"button\" style=\"width:100px;\" onclick=\"updateAddress(this);\">수정</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"btn-submit\" style=\"width: 115px; border-top:0\"><button type=\"submit\" style=\"width:100px;\">완료</button></td>\r\n");
      out.write("\t\t\t\t\t\t<td  style=\"width: 300px; border-top:0\"><button type=\"button\" style=\"width:100px;\" onclick=\"deleteAddress(this);\">삭제</button></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<div><button type=\"button\" id=\"btn-insertAddr\">관심지역 추가</button></div>\r\n");
      out.write("\t\t\t\t<div class=\"btn-wrap\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn-2\" id=\"btn-mainPage\">뒤로가기</button> \r\n");
      out.write("\t\t\t\t\t<button class=\"btn-2\" id=\"btn-updateMember\" type=\"button\">수정</button> \r\n");
      out.write("\t\t\t\t\t<button class=\"btn-2\" id=\"btn-deleteMember\">탈퇴</button> \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<div class=\"modal fade\" id=\"myModal\" role=\"dialog\" >\r\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-div\">\r\n");
      out.write("\t\t\t\t<!-- Modal content-->\r\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form action=\"/addAddrInMypage\" method=\"get\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"padding: 50px 50px; text-align: center; border: 0px; padding-bottom: 0px\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/img/tomatoMarketLogo.png\" width=\"30\" height=\"34\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-size: 1.5em; margin-top: 15px;\">토마토마켓을 이용해주셔서\r\n");
      out.write("\t\t\t\t\t\t\t감사합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p>회원님의 관심지역을 선택해주세요!</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\" style=\"padding: 40px 192px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"div-choiceAddr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"addrEmail\"value=\"");
      out.print(m.getEmail());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"addCity\" style=\"width: 90px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value='서울'>서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"addGungu\" style=\"width: 120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option selected disabled hidden>-선택-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강남구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>강서구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>관악구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>광진구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>구로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>금천구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>노원구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>도봉구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>동대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>동작구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>마포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>서대문구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>서초구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>성동구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>성북구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>송파구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>양청구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>영등포구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>용산구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>은평구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>종로구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>중구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>중랑구</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button class=\"addressAdd-btn\" id=\"complete\" type=\"submit\">완료</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Modal end -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer/footer.css\">\r\n");
      out.write("   <footer class=\"footerMain\">\r\n");
      out.write("      <div class=\"footer1\">\r\n");
      out.write("         <div class=\"con\">\r\n");
      out.write("            <a href=\"/notice?noticeNum=0\">공지사항</a><span>|</span>\r\n");
      out.write("            <a href=\"/notice?noticeNum=1\">운영정책</a><span>|</span>\r\n");
      out.write("            <a href=\"#\">광고센터</a><span>|</span> \r\n");
      out.write("            <a href=\"/noticeMTMSelect\">1:1문의</a><span>|</span>\r\n");
      out.write("            <a href=\"#\">사업자정보확인</a><span>|</span>\r\n");
      out.write("            <a href=\"#\">이용약관</a><span>|</span>\r\n");
      out.write("            <a href=\"#\">개인정보처리방침</a><span>|</span>\r\n");
      out.write("            <a href=\"#\">위치기반서비스약관</a>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>   \r\n");
      out.write("      <div class=\"footer2\">\r\n");
      out.write("         <div class=\"con\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("               <div class=\"logo\"><img src=\"/img/tomatoLogo.png\"></div>\r\n");
      out.write("               <span class=\"compony-intro span\">No.1 중고 거래 웹사이트 토마토 마켓. 누구나, 무엇이든 쉽고 편하고 안전하게 거래하는 세상을 꿈꾸고 있습니다.</span>\r\n");
      out.write("               <div class=\"footer-sns-icon\">\r\n");
      out.write("                  <a href=\"#\"><img src=\"/img/facebook.png\"></a>\r\n");
      out.write("                  <a href=\"#\"><img src=\"/img/blog.png\"></a>\r\n");
      out.write("                  <a href=\"#\"><img src=\"/img/instagram.png\"></a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-desc\">\r\n");
      out.write("               <span class=\"span\">\r\n");
      out.write("                  대표이사:OOO개인정보 담당자:OOO사업자등록번호:123-45-67891통신판매업신고:2019-서울서초-1234<br>\r\n");
      out.write("                  주소:서울특별시 영등포구 선유동2로 57 이레빌딩(구관) 19F, 20F TEL: 1544-9970 / FAX: 02-2163-8560<br>\r\n");
      out.write("                  토마토마켓(주)는 통신판매중개자로서 중고거래마켓 토마토마켓의 거래 당사자가 아니며, 입점 판매가 등록한 상품정보 및 거래에 대해 책임을 지지 않습니다.\r\n");
      out.write("               </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("               <div class=\"footer-copyright\">Copyright ⓒ TOMATOMARKET Corp. All rights reserved.</div>\r\n");
      out.write("               <div class=\"footer-end\"><span class=\"span\">고객센터</span><span class=\"span\">cs@tomato.co.kr</span><span class=\"span\">제휴문의</span> <span class=\"span\">partner@tomato.co.kr</span></div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t//다음 api를 이용한 주소 찾기\r\n");
      out.write("\tfunction addrSearch() {\r\n");
      out.write("\t\tnew daum.Postcode({\r\n");
      out.write("\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t$(\"#zipCode\").val(data.zonecode);\r\n");
      out.write("\t\t\t\t$(\"#addr\").val(data.roadAddress);\r\n");
      out.write("\t\t\t\t$(\"#addr\").val(data.jibunAddress);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}).open();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 관심 주소 수정\r\n");
      out.write("\tfunction updateAddress(updateBtn){\r\n");
      out.write("\t\t$(updateBtn).parent().prev().show();\r\n");
      out.write("\t\t$(updateBtn).parent().prev().prev().show();\r\n");
      out.write("\t\t$(updateBtn).parent().siblings().eq(2).hide();\r\n");
      out.write("\t\t$(updateBtn).parent().siblings().eq(3).hide();\r\n");
      out.write("\t\t$(updateBtn).parent().hide();\r\n");
      out.write("\t\t$(updateBtn).parent().next().show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteAddress(deleteBtn){\r\n");
      out.write("\t\tvar email = $(\"#email\").val();\r\n");
      out.write("\t\tvar gungu = $(deleteBtn).parent().siblings().eq(3).children().eq(0).val();\r\n");
      out.write("\t\tconsole.log(gungu);\r\n");
      out.write("\t\tlocation.href=\"/deleteAddress?email=\"+email+\"&gungu=\"+gungu+\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 관심지역추가Btn 누르면 관심지역추가Modal 나타남 \r\n");
      out.write("\t\t$(\"#btn-insertAddr\").click(function(){\r\n");
      out.write("\t\t\t$('#myModal').modal('show');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".newCity\").hide();\r\n");
      out.write("\t\t$(\".newGungu\").hide();\r\n");
      out.write("\t\t$(\".btn-submit\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#btn-mainPage\").click(function(){\r\n");
      out.write("\t\t\tlocation.href=\"/\";\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 회원 탈퇴\r\n");
      out.write("\t\t$(\"#btn-deleteMember\").click(function(){\r\n");
      out.write("\t\t\tvar email = $(\"#email\").val();\r\n");
      out.write("\t\t\tconsole.log(email);\r\n");
      out.write("\t\t\tlocation.href=\"/deleteMember?email=\"+email+\"\";\r\n");
      out.write("\t\t})\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t// 비밀번호, 핸드폰 번호 정규표현식\r\n");
      out.write("\t\tvar regExpPassword = /^(?=.*[A-Za-z])(?=.*[0-9])[A-Za-z0-9]{6,}$/;\r\n");
      out.write("\t\tvar regExpPhone = /^01(?:0|1|[6-9])-(?:[0-9]{3}|[0-9]{4})-[0-9]{4}$/;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// password 정규표현식 확인\r\n");
      out.write("\t\t$(\"#pw\").change(function(){\r\n");
      out.write("\t\t\tvar pw = $(\"#pw\").val();\r\n");
      out.write("\t\t\tvar msg = $(\"#chkMsg3\");\r\n");
      out.write("\t\t\tif(!regExpPassword.test(pw)){\r\n");
      out.write("\t\t\t\tmsg.html('* 6자 이상의 영문, 숫자 사용');\r\n");
      out.write("\t\t\t\tmsg.css('color', 'red');\r\n");
      out.write("\t\t\t\tmsg.attr('status','0');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmsg.html('');\r\n");
      out.write("\t\t\t\tmsg.attr('status','1');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\t// password 재확인\r\n");
      out.write("\t\t$(\"#rePw\").change(function(){\r\n");
      out.write("\t\t\tvar pw = $(\"#rePw\").val();\r\n");
      out.write("\t\t\tvar msg = $(\"#chkMsg4\");\r\n");
      out.write("\t\t\tif(!(pw===$(\"#pw\").val())){\r\n");
      out.write("\t\t\t\tmsg.html('* 비밀번호 확인항목의 값이 일치하지 않습니다.');\r\n");
      out.write("\t\t\t\tmsg.css('color', 'red');\r\n");
      out.write("\t\t\t\tmsg.attr('status','0');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmsg.html('');\r\n");
      out.write("\t\t\t\tmsg.attr('status','1');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// phone 정규표현식 확인\r\n");
      out.write("\t\t$(\"#phone\").change(function(){\r\n");
      out.write("\t\t\tvar pw = $(\"#phone\").val();\r\n");
      out.write("\t\t\tvar msg = $(\"#chkMsg5\");\r\n");
      out.write("\t\t\tif($(\"#phone\").val()==\"\"){\r\n");
      out.write("\t\t\t\tmsg.html('');\r\n");
      out.write("\t\t\t\tmsg.attr('status','1');\r\n");
      out.write("\t\t\t}else if(!regExpPhone.test(pw)){\r\n");
      out.write("\t\t\t\tmsg.html('‘-’ 를 포함하여 10~11자리 번호를 입력해주세요.');\r\n");
      out.write("\t\t\t\tmsg.css('color', 'red');\r\n");
      out.write("\t\t\t\tmsg.attr('status','0');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tmsg.html('');\r\n");
      out.write("\t\t\t\tmsg.attr('status','1');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 수정 button 실행 조건\r\n");
      out.write("\t\t$(\"#btn-updateMember\").click(function(){\r\n");
      out.write("\t\t\t\tvar email = $(\"#email\").val();\r\n");
      out.write("\t\t\t\tvar pw = $(\"#pw\").val();\r\n");
      out.write("\t\t\t\tvar rePw = $(\"#rePw\").val();\r\n");
      out.write("\t\t\t\tvar phone = $(\"#phone\").val();\r\n");
      out.write("\t\t\t\tvar addr = $(\"#addr\").val();\r\n");
      out.write("\t\t\t\tvar zipCode = $(\"#zipCode\").val();\r\n");
      out.write("\t\t\t\tvar detailAddr = $(\"#detailAddr\").val();\r\n");
      out.write("\t\t\t\tvar name = $(\"#memberName\").val();\r\n");
      out.write("\t\t\t\tvar memberBank = $(\"#memberBank\").val();\r\n");
      out.write("\t\t\t\tvar memberAccount = $(\"#memberAccount\").val();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar address = addr+\"/\"+detailAddr;\t//주소 = 주소/상세주소\r\n");
      out.write("\t\t\t\tconsole.log(address);\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tif(pw==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#pw\").focus();\r\n");
      out.write("\t\t\t\t\t$(\"#chkMsg3\").html('* 비밀번호항목은 필수 정보입니다.');\r\n");
      out.write("\t\t\t\t\t$(\"#chkMsg3\").css('color', 'red');\r\n");
      out.write("\t\t\t\t}else if(rePw==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호확인 항목을 입력해주세요\");\r\n");
      out.write("\t\t\t\t\t$(\"#codeCheck\").focus();\r\n");
      out.write("\t\t\t\t\t$(\"#chkMsg4\").html('* 비밀번호확인 항목은 필수 정보입니다.');\r\n");
      out.write("\t\t\t\t\t$(\"#chkMsg4\").css('color', 'red');\r\n");
      out.write("\t\t\t\t}else if($(\"#chkMsg3\").attr('status')=='0'){\r\n");
      out.write("\t\t\t\t\t$(\"#pw\").focus();\r\n");
      out.write("\t\t\t\t}else if($(\"#chkMsg4\").attr('status')=='0'){\r\n");
      out.write("\t\t\t\t\t$(\"#rePw\").focus();\r\n");
      out.write("\t\t\t\t}else if($(\"#chkMsg5\").attr('status')=='0'){\r\n");
      out.write("\t\t\t\t\t$(\"#phone\").focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\tconsole.log(\"정보 수정중..\");\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl:\"/ajaxUpdateMember\",\r\n");
      out.write("\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\tdata:{email:email, pw:pw, phone:phone, zipCode:zipCode, address:address, name:name, memberBank:memberBank, memberAccount:memberAccount},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\t\tif(data!=0){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"사용자 정보 수정 성공\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"사용자 정보 수정 실패!\");\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}, error : function(){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"사용자 정보 수정 error\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
